### ISSUE TITLE
Menu item text containing ‘_’ is interpreted as containing keyboard shortcuts

### ISSUE THREAD

**Issue by dsalt** [JGRennison/yarssr#1]
Fixable with `$title =~ s/_/__/g;` prior to creating the menu item. Needs to be done for the feed submenu content; should be done for the feed menu titles too.

For examples of ‘_’ in article titles, see Phoronix.

**Comment by JGRennison** [comment]
This should be fixed now. There's a Gtk method to create menu items which doesn't enable underscore mnemonics which I've used instead.
