### ISSUE TITLE
Open multiple items

### ISSUE THREAD

**Issue by jangregor** [JGRennison/yarssr#2]
Hi,

I have created a small patch to yarssr that enables opening all unread items with one click. I added menu items to work on a per-feed or global basis. It is a bit rough implementation, pretty much just serving my own purpose. Icon is not working, as I did not need it for myself, I just needed the functionality :) . Also not sure if the implementation is 100% consistent with your original design.
Feel free to review/fix/merge.

Submitted also to original (not sure if maintained codebase) https://sourceforge.net/p/yarssr/patches/3/.

Jan
[yarssr_open_multi.patch.gz](https://github.com/JGRennison/yarssr/files/1487075/yarssr_open_multi.patch.gz)

**Comment by JGRennison** [comment]
The patch references a Yarssr::Browser module which doesn't seem to be in the patch or in the original source code.
Which revision did you base this on?

This feature seems a reasonable thing to add in principle.

**Comment by jangregor** [comment]
Yarssr::Browser is a new class I created, as it is called from multiple places. Should have been included in the patch, but apparently I screwed up. Attaching fixed patch.
[yarssr_open_multi.patch.gz](https://github.com/JGRennison/yarssr/files/1497274/yarssr_open_multi.patch.gz)

**Comment by JGRennison** [comment]
I've done some modifications/refactoring and have added this as commit e70eb9f.
Thanks again for your contribution.
