### ISSUE TITLE
Gui.pm : `use Yarssr::Browser` but no Browser.pm file

### ISSUE THREAD

**Issue by xurei** [JGRennison/yarssr#3]
I'm trying to build the code from source, but I get this error :
```
Can't locate Yarssr/Browser.pm in @INC
```

Any idea ?

**Comment by JGRennison** [comment]
After building using `make`, you will probably need to install it using `make install` or `sudo make install` before you'll be able to run it.
This places the modules in the path / `@INC` where they can be found.
Once installed you should be able to run it by simply running `yarssr`.

**Comment by JGRennison** [comment]
Fixed by 134ebe09be9e25f2bdfd6458389c82ff953d36d7
